# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUÇÃO AO PYTHON
---

# 1.1 Introdução

> Python é uma linguagem de programação de alto nível com suporte a múltiplos paradigmas de programação. É um projeto *open source* e desde seu surgimento, em 1991, vem se tornando uma das linguagens de programação interpretadas mais populares. 
>
> Nos últimos anos Python desenvolveu uma comunidade ativa de processamento científico e análise de dados e vem se destacando como uma das linguagens mais relevantes quando o assunto é ciência de dados e machine learning, tanto no ambiente acadêmico como também no mercado.

# 1.2 Instalação e ambiente de desenvolvimento

### Instalação Local

### https://www.python.org/downloads/
### ou
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versão

In [264]:
!python --version

Python 3.7.12


# 1.3 Trabalhando com arrays Numpy

In [265]:
import numpy as np

In [266]:
km = np.loadtxt('carros-km.txt')
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [267]:
anos = np.loadtxt('carros-anos.txt', dtype=int)
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtendo a quilometragem média por ano

In [268]:
km_media = km / (2022 - anos)

In [269]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

In [270]:
type(km_media)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DA LINGUAGEM
---

# 2.1 Operações matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Adição ($+$)

In [271]:
2 + 2

4

### Subtração ($-$)

In [272]:
2-2

0

### Multiplicação ($*$)

In [273]:
2*3

6

### Divisão ($/$) e ($//$)
A operação divisão sempre retorna um número de ponto flutuante

In [274]:
10/3

3.3333333333333335

In [275]:
10//3

3

### Exponenciação ($**$)

In [276]:
2**3

8

### Resto da divisão ($\%$)

In [277]:
10 % 3

1

In [278]:
4% 2

0

### Expressões matemáticas

In [279]:
5*2+3*2

16

In [280]:
(5*2)+(3*2)

16

In [281]:
5*(2+3)*2

50

### A variável _

No modo interativo, o último resultado impresso é atribuído à variável _

In [282]:
5*2

10

In [283]:
_ +3*2

16

In [284]:
_/2

8.0

In [285]:
10%2+3//10

0

In [286]:
5*(2+3)/2

12.5

In [287]:
2**3*4

32

# 2.2 Variáveis 

### Nomes de variáveis

- Nomes de variáveis pode começar com letras (a - z, A - Z) ou o caractere *underscore* (_):

    > Altura
    >
    > _peso
    
- O restante do nome pode conter letras, números e o caractere "_":

    > nome_da_variavel
    >
    > _valor
    >
    > dia_28_11_
    

- O nomes são *case sensitive*:

    > Nome_Da_Variável $\ne$ nome_da_variavel $\ne$ NOME_DA_VARIAVEL
    
### <font color=red>Observações:
- Existem algumas palavras reservadas da linguagem que não podem ser utilizadas como nomes de variável:

| |Lista de palavras <br>reservadas em Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           | 
| assert        | finally      | or            | 
| break         | for          | pass          | 
| class         | from         | nonlocal      | 
| continue      | global       | raise         | 
| def           | if           | return        | 
| del           | import       | try           | 
| elif          | in           | while         | 
| else          | is           | with          | 
| except        | lambda       | yield         | 
| False         | True         | None          | 

### Declaração de variáveis

### Operadores de atribuição: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [288]:
ano_atual = 2022
ano_fab = 2003
km_total = 4410.0

In [289]:
ano_atual

2022

In [290]:
ano_fab

2003

In [291]:
km_total

4410.0

# $$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

### Operações com variáveis

In [292]:
km_media = km_total / (ano_atual - ano_fab)

In [293]:
km_media

232.10526315789474

In [294]:
ano_atual = 2022
ano_fab = 2003
km_total = 4410.0
km_media = km_total / (ano_atual - ano_fab)
km_total = km_total + km_media
km_total

4642.105263157895

In [295]:
ano_atual = 2022
ano_fab = 2003
km_total = 4410.0
km_media = km_total / (ano_atual - ano_fab)
km_total += km_media
km_total

4642.105263157895

### Conclusão:
```
"valor = valor + 1" é equivalente a "valor += 1"
```

### Declaração múltipla

In [296]:
ano_atual, ano_fab, km_total = 2022, 2003, 4410.0
km_media = km_total / (ano_atual - ano_fab)
km_total = km_total + km_media
km_total

4642.105263157895

# 2.3 Tipos de dados

Os tipos de dados especificam como números e caracteres serão armazenados e manipulados dentro de um programa. Os tipos de dados básicos do Python são:

1. **Números**
    1. ***int*** - Inteiros
    - ***float*** - Ponto flutuante
- **Booleanos** - Assume os valores True ou False. Essencial quando começarmos a trabalhar com declarações condicionais
- ***Strings*** - Sequência de um ou mais caracteres que pode incluir letras, números e outros tipos de caracteres. Representa um texto.
- **None** - Representa a ausência de valor

### Números

In [297]:
ano_atual = 2022

In [298]:
type(ano_atual)

int

In [299]:
km_total = 4410.0

In [300]:
type(km_total)

float

### Booleanos

In [301]:
zero_km = True

In [302]:
type(zero_km)

bool

In [303]:
zero_km = False

In [304]:
type(zero_km)

bool

### Strings

In [305]:
nome = 'NOME'

In [306]:
type(nome)

str

In [307]:
nome_2 = "Nome"

In [308]:
type(nome_2)

str

In [309]:
nome_3 = "Nome 'meu' é"
nome_3

"Nome 'meu' é"

In [310]:
nome_4 = 'Nome "meu" é'
nome_4

'Nome "meu" é'

In [311]:
carros = '''
  nome
  idade 
  nota
'''
carros

'\n  nome\n  idade \n  nota\n'

### None

In [312]:
quilometragem = None

In [313]:
type(quilometragem)

NoneType

# 2.4 Conversão de tipos

In [314]:
a = 10
b = 20
c = 'Python é '
d = 'legal'

In [315]:
type(a)

int

In [316]:
type(b)

int

In [317]:
type(c)

str

In [318]:
type(d)

str

In [319]:
a+b

30

In [320]:
c+d

'Python é legal'

### Conversões de tipo

Funções int(), float(), str()

In [321]:
str(a)

'10'

In [322]:
type(str(a))

str

In [323]:
c + str(a)

'Python é 10'

In [324]:
float(a)

10.0

In [325]:
var = 3.14

In [326]:
type(var)

float

In [327]:
int(var)

3

In [328]:
var2 = 3.98

In [329]:
type(var2)

float

In [330]:
int(var2)

3

In [331]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [332]:
#'A quilometragem média do veículo é 5000 km'
text + str(int(Km/(Ano_atual - Ano_fabricacao))) + ' km'

'A quilometragem média do veículo é 5000 km'

# 2.5 Indentação, comentários e formatação de *strings*

### Indentação

Na linguagem Python os programas são estruturados por meio de indentação. Em qualquer linguagem de programação a prática da indentação é bastante útil, facilitando a leitura e também a manutenção do código. Em Python a indentação não é somente uma questão de organização e estilo, mas sim um requisito da linguagem.

In [333]:
ano_atual = 2019
ano_fabricacao = 2019

if (ano_atual == ano_fabricacao):
    print('Verdadeiro')
else:
    print('Falso')

Verdadeiro


### Comentários

Comentários são extremamente importantes em um programa. Consiste em um texto que descreve o que o programa ou uma parte específica do programa está fazendo. Os comentários são ignorados pelo interpretador Python. 

Podemos ter comentários de uma única linha ou de múltiplas linhas.

In [334]:
# Isto é um comentário
ano_atual = 2019
ano_atual

2019

In [335]:
# Isto
# é um 
# comentário
ano_atual = 2019
ano_atual

2019

In [336]:
'''Isto é um
comentário'''
ano_atual = 2019
ano_atual

2019

In [337]:
# Definindo variáveis
ano_atual = 2019
ano_fabricacao = 2019

'''
Estrutura condicional que vamos 
aprender na próxima aula
'''
if (ano_atual == ano_fabricacao):   # Testando se condição é verdadeira
    print('Verdadeiro')
else:                               # Testando se condição é falsa
    print('Falso')

Verdadeiro


### Formatação de *strings*

## *str % valor*
https://docs.python.org/3.6/library/stdtypes.html#old-string-formatting

In [338]:
print('%(language)s has %(number)03d quote types.' %
      {'language': "Python", "number": 2})

Python has 002 quote types.


In [339]:
print('Olá, %(nome)s'%{'nome':"Você"})

Olá, Você


In [340]:
print('Olá,  %(nome)s. Esse é seu acesso número %(num)05d'%{'nome':'Você','num': 32})

Olá,  Você. Esse é seu acesso número 00032


In [341]:
print('Olá,  %(nome)s. Esse é seu acesso número %(num)i'%{'nome':'Você','num': 32})

Olá,  Você. Esse é seu acesso número 32


In [342]:
print('Olá,  %(nome)s. O valor da sua compra é %(val).2f'%{'nome':'Você','val': 32})

Olá,  Você. O valor da sua compra é 32.00


In [343]:
print('Olá,  %(nome)s. O valor da sua compra é %(val)f'%{'nome':'Você','val': 32})

Olá,  Você. O valor da sua compra é 32.000000


In [344]:
print('Olá,  %(nome)s. O valor da sua compra é %(val)g'%{'nome':'Você','val': 1234567890})

Olá,  Você. O valor da sua compra é 1.23457e+09


## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [345]:
print('Olá, {}'.format('Você'))

Olá, Você


In [346]:
print('Olá, {}. Esse é seu acesso número {}'.format('Você', 32))

Olá, Você. Esse é seu acesso número 32


In [347]:
print('Olá, {nome}. Esse é seu acesso número {num}'.format(nome = 'Você', num = 32))

Olá, Você. Esse é seu acesso número 32


In [348]:
print('Olá, {0}. Esse é seu acesso número {1}'.format('Você', 32))

Olá, Você. Esse é seu acesso número 32


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [349]:
nome = 'Você'
num = 32

In [350]:
print(f'Olá, {nome}. Esse é seu acesso número {num}')

Olá, Você. Esse é seu acesso número 32


In [351]:
print('Olá, {nome}! Este é seu acesso de número {acessos}'.format(acessos = 32, nome = 'Rodrigo'))

Olá, Rodrigo! Este é seu acesso de número 32


# <font color=green> 3. TRABALHANDO COM LISTAS
---

# 3.1 Criando listas

Listas são sequências **mutáveis** que são utilizadas para armazenar coleções de itens, geralmente homogêneos. Podem ser construídas de várias formas:
```
- Utilizando um par de colchetes: [ ], [ 1 ]
- Utilizando um par de colchetes com itens separados por vírgulas: [ 1, 2, 3 ]
```

In [352]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [353]:
type(Acessorios)

list

### Lista com tipos de dados variados

In [354]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [355]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [356]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
 106161.94]

In [357]:
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

# 3.2 Operações com listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Retorna **True** se um elemento da lista *A* for igual a *x*.

In [358]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [359]:
'Rodas de liga' in Acessorios

True

In [360]:
'Rodas de liga leve' in Acessorios

False

In [361]:
'Rodas de liga leve' not in Acessorios

True

## *A + B*

Concatena as listas *A* e *B*.

In [362]:
A = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']
B = ['Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [363]:
A

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro']

In [364]:
B

['Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [365]:
A + B

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *len(A)*

Tamanho da lista A.

In [366]:
len(A)

4

In [367]:
len(Acessorios)

8

In [368]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [369]:
'2003' in carro

False

In [370]:
'Rodas de liga' in carro

False

In [371]:
'False' not in carro

True

# 3.3 Seleções em listas

## *A[ i ]*

Retorna o i-ésimo item da lista *A*.

<font color=red>**Observação:**</font> Listas têm indexação com origem no zero.

In [372]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [373]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [374]:
Acessorios[0]

'Rodas de liga'

In [375]:
Acessorios[1]

'Travas elétricas'

In [376]:
Acessorios[-1]

'Sensor de chuva'

In [377]:
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [378]:
Carros[0][0]

'Jetta Variant'

In [379]:
Carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [380]:
Carros[0][-2][1]

'Travas elétricas'

## *A[ i : j ]*

Recorta a lista *A* do índice i até o j. Neste fatiamento o elemento com índice i é **incluído** e o elemento com índice j **não é incluído** no resultado.

In [381]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [382]:
Acessorios[2:5]

['Piloto automático', 'Bancos de couro', 'Ar condicionado']

In [383]:
Acessorios[2:6]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento']

In [384]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [385]:
Acessorios[:5]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [386]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [387]:
letras[:2]

['A', 'B']

In [388]:
letras[2:5]

['C', 'D', 'E']

In [389]:
letras[5:]

['F', 'G', 'H']

In [390]:
letras[-3:]

['F', 'G', 'H']

In [391]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

In [392]:
carros[1][3]

True

In [393]:
carros[1][4][1]

'Teto panorâmico'

In [394]:
carros[1][-1][-2]

'Teto panorâmico'

In [395]:
carros[0][4]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [396]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

# 3.4 Métodos de listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

In [397]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## *A.sort()*

Ordena a lista *A*.

In [398]:
Acessorios.sort()
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [399]:
Acessorios.sort(reverse=True)
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Rodas de liga',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

## *A.append(x)*

Adiciona o elemnto *x* no final da lista *A*.

In [400]:
Acessorios.append("4x4")
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Rodas de liga',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 '4x4']

## *A.pop(i)*

Remove e retorna o elemento de índice i da lista *A*.

<font color=red>**Observação:**</font> Por *default* o método *pop()* remove e retorna o último elemento de uma lista.

In [401]:
Acessorios.pop()

'4x4'

In [402]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Rodas de liga',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [403]:
Acessorios.pop(4)

'Rodas de liga'

In [404]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

## *A.copy()*

Cria uma cópia da lista *A*.

<font color=red>**Observação:**</font> O mesmo resultado pode ser obtido com o seguinte código: 
```
A[:]
```

In [405]:
#usa a mesma referência em memmória, por isso modifica ambas
Acessorios_2 = Acessorios 
Acessorios_2

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [406]:
Acessorios_2.append("4x4")
Acessorios_2

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 '4x4']

In [407]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 '4x4']

In [408]:
Acessorios.pop()

'4x4'

In [409]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [410]:
Acessorios_2

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [411]:
Acessorios_3 = Acessorios.copy()
Acessorios_3

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [412]:
Acessorios_3.append("4x4")

In [413]:
Acessorios_3

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 '4x4']

In [414]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [415]:
#igual ao copy()
Acessorios_4 = Acessorios[:]
Acessorios_4

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [416]:
Acessorios_4.pop()

'Ar condicionado'

In [417]:
Acessorios_4

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro']

In [418]:
Acessorios

['Travas elétricas',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Sensor crepuscular',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado']

In [419]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

In [420]:
Acessorios.append("Airbag")
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Airbag']

In [421]:
Acessorios.append("Vidros elétricos")
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Airbag',
 'Vidros elétricos']

In [422]:
Acessorios.sort()
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros elétricos']

In [423]:
Acessorios.pop(-2)

'Travas elétricas'

In [424]:
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

In [425]:
dados = [1, 2, 3, 4]
dados_copia = dados
dados_copia.append(5)

In [426]:
dados

[1, 2, 3, 4, 5]

# <font color=green> 4. ESTRUTURAS DE REPETIÇÃO E CONDICIONAIS
---

# 4.1 Instrução *for*

#### Formato padrão

```
for <variável> in <coleção>:
    <instruções>
```

### Loops com listas

In [427]:
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']

In [428]:
for item in Acessorios:
  print(item)

Airbag
Ar condicionado
Bancos de couro
Piloto automático
Rodas de liga
Vidros elétricos


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [429]:
range(0, 10)

range(0, 10)

In [430]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [431]:
for i in range(10):
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [432]:
quadrado = []
for i in range(10):
  quadrado.append(i**2)
quadrado  

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [433]:
quad = [i**2 for i in range(10)]

In [434]:
quad

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [435]:
quadrado = []
for i in range(10):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [436]:
quad = [i**2 for i in range(10)]
quad

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops aninhados

In [437]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [438]:
for lista in dados:
  print(lista)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento']
['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [439]:
for lista in dados:
  for item in lista:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [440]:
Acessorios = []

for lista in dados:
  for item in lista:
    Acessorios.append(item)

In [441]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [442]:
list(set(Acessorios))

['Câmbio automático',
 'Vidros elétricos',
 'Painel digital',
 'Sensor crepuscular',
 'Controle de estabilidade',
 'Bancos de couro',
 'Ar condicionado',
 'Teto panorâmico',
 'Piloto automático',
 'Sensor de chuva',
 'Freios ABS',
 'Travas elétricas',
 'Rodas de liga',
 'Sensor de estacionamento',
 '4 X 4',
 'Central multimídia',
 'Câmera de estacionamento']

### List comprehensions

In [443]:
[item for lista in dados for item in lista]

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

In [444]:
list(set([item for lista in dados for item in lista]))

['Câmbio automático',
 'Vidros elétricos',
 'Painel digital',
 'Sensor crepuscular',
 'Controle de estabilidade',
 'Bancos de couro',
 'Ar condicionado',
 'Teto panorâmico',
 'Piloto automático',
 'Sensor de chuva',
 'Freios ABS',
 'Travas elétricas',
 'Rodas de liga',
 'Sensor de estacionamento',
 '4 X 4',
 'Central multimídia',
 'Câmera de estacionamento']

In [445]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [446]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [447]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [448]:
[item for lista in dados for item in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

# 4.3 Instrução *if*

#### Formato padrão

```
if <condição>:
     <instruções caso a condição seja verdadeira>
```

### Operadores de comparação: $==$, $!=$, $>$, $<$, $>=$, $<=$
### e
### Operadores lógicos: $and$, $or$, $not$

In [449]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [450]:
for lista in dados:
  print(lista[2])

False
False
False
True
False
False
True
False
False
False


In [451]:
for lista in dados:
  if lista[2] == True:
    print(lista)

['DS5', 2019, True]
['A5', 2019, True]


In [452]:
zero_km_y = []
for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
zero_km_y    

[['DS5', 2019, True], ['A5', 2019, True]]

In [453]:
zero_km_y = []
for lista in dados:
  if lista[2] == False:
    zero_km_y.append(lista)
zero_km_y    

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### List comprehensions

In [454]:
[lista for lista in dados if lista[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [455]:
[lista for lista in dados if lista[2] == False]

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.4 Instruções *if-else* e *if-elif-else*

#### Formato padrão

```
if <condição>:
    <instruções caso a condição seja verdadeira>
else:
    <instruções caso a condição não seja verdadeira>
```

In [456]:
zero_km_y, zero_km_n = [], []
for lista in dados:
  if lista[2] == True:
    zero_km_y.append(lista)
  else:
    zero_km_n.append(lista)
print(zero_km_y)
print(zero_km_n)

[['DS5', 2019, True], ['A5', 2019, True]]
[['Jetta Variant', 2003, False], ['Passat', 1991, False], ['Crossfox', 1990, False], ['Aston Martin DB4', 2006, False], ['Palio Weekend', 2012, False], ['Série 3 Cabrio', 2009, False], ['Dodge Jorney', 2019, False], ['Carens', 2011, False]]


#### Formato padrão

```
if <condição 1>:
    <instruções caso a condição 1 seja verdadeira>
elif <condição 2>:
    <instruções caso a condição 2 seja verdadeira>
elif <condição 3>:
    <instruções caso a condição 3 seja verdadeira>
                        .
                        .
                        .
else:
    <instruções caso as condições anteriores não sejam verdadeiras>
```

In [457]:
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [458]:
print('AND')
print(f'(True and True) o resultado é: {True and True}')
print(f'(True and False) o resultado é: {True and False}')
print(f'(False and True) o resultado é: {False and True}')
print(f'(False and False) o resultado é: {False and False}')

AND
(True and True) o resultado é: True
(True and False) o resultado é: False
(False and True) o resultado é: False
(False and False) o resultado é: False


In [459]:
print('OR')
print(f'(True or True) o resultado é: {True or True}')
print(f'(True or False) o resultado é: {True or False}')
print(f'(False or True) o resultado é: {False or True}')
print(f'(False or False) o resultado é: {False or False}')

OR
(True or True) o resultado é: True
(True or False) o resultado é: True
(False or True) o resultado é: True
(False or False) o resultado é: False


In [460]:
a, b, c = [], [], []
for lista in dados:
  if (lista[1] <= 2000):
    a.append(lista)
  elif (lista[1] > 2000 and lista[1] <= 2010):
    b.append(lista)
  else:
    c.append(lista)

In [461]:
a

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [462]:
b

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [463]:
c

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [464]:
a, b, c = [], [], []
for lista in dados:
  if (lista[1] <= 2000):
    a.append(lista)
  elif (2000 < lista[1] <= 2010):
    b.append(lista)
  else:
    c.append(lista)

In [465]:
a

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [466]:
b

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [467]:
c

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# <font color=green> 5. NUMPY BÁSICO
---

Numpy é a abreviação de Numerical Python e é um dos pacotes mais importantes para processamento numérico em Python. Numpy oferece a base para a maioria dos pacotes de aplicações científicas que utilizem dados numéricos em Python (estruturas de dados e algoritmos). Pode-se destacar os seguintes recursos que o pacote Numpy contém:

- Um poderoso objeto array multidimensional;
- Funções matemáticas sofisticadas para operações com arrays sem a necessidade de utilização de laços *for*;
- Recursos de algebra linear e geração de números aleatórios

Além de seus óbvios usos científicos, o pacote NumPy também é muito utilizado em análise de dados como um eficiente contêiner multidimensional de dados genéricos para transporte entre diversos algoritmos e bibliotecas em Python.

**Versão:** 1.16.5

**Instalação:** https://scipy.org/install.html

**Documentação:** https://numpy.org/doc/1.16/

### Pacotes

Existem diversos pacotes Python disponíveis para download na internet. Cada pacote tem como objetivo a solução de determinado tipo de problema e para isso são desenvolvidos novos tipos, funções e métodos.

Alguns pacotes são bastante utilizados em um contexto de ciência de dados como por exemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Alguns pacotes não são distribuídos com a instalação default do Python. Neste caso devemos instalar os pacotes que necessitamos em nosso sistema para podermos utilizar suas funcionalidades.

### Importando todo o pacote

In [468]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [469]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo o pacote e atribuindo um novo nome 

In [470]:
import numpy as np

In [471]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte do pacote

In [472]:
from numpy import arange

In [473]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Criando arrays Numpy

In [474]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [475]:
km = np.array([1000, 2000, 4007, 1500])

In [476]:
km

array([1000, 2000, 4007, 1500])

In [477]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [478]:
km.dtype

dtype('int64')

### A partir de dados externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [479]:
km = np.loadtxt(fname = 'carros-km.txt', dtype=int)

In [480]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [481]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [482]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [483]:
acessorios = np.array(dados)

In [484]:
acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [485]:
km.shape

(258,)

In [486]:
acessorios.shape

(3, 8)

### Comparando desempenho com listas

In [487]:
np_array = np.arange(1000000)

In [488]:
np_list = list(range(1000000))

In [489]:
%time for _ in range(100): np_array*=2

CPU times: user 99.1 ms, sys: 13.4 ms, total: 112 ms
Wall time: 154 ms


In [490]:
%time for _ in range(100): np_list = [x*2 for x in np_list]

CPU times: user 7.88 s, sys: 1.37 s, total: 9.25 s
Wall time: 10.3 s


# 5.2 Operações aritméticas com arrays Numpy

### Operações entre arrays e constantes

In [491]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [492]:
idade = [2022 - ano for ano in anos]
idade

[19, 31, 32, 3, 16]

In [493]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [494]:
idade = 2022 - anos
idade

array([19, 31, 32,  3, 16])

### Operações entre arrays

In [495]:
km_medio = km/idade

In [496]:
km_medio

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

In [497]:
44410./19

2337.3684210526317

### Operações com arrays de duas dimensões

In [498]:
dados = np.array([km, anos])

In [499]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [500]:
dados.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [501]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [502]:
dados[0][1]

5712.0

In [503]:
km_medio = dados[0]/(2022 - dados[1])
km_medio

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

# 5.3 Seleções com arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [506]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexação 

<font color=red>**Observação:**</font> A indexação tem origem no zero.

In [507]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [509]:
contador[0]

0

In [510]:
item = 6
item = item -1
contador[item]

5

In [511]:
contador[-1]

9

In [512]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [513]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

## <font color=green>**Dica:**</font>
### *ndarray[ linha ][ coluna ]* ou *ndarray[ linha, coluna ]*

In [514]:
dados[1][2]

1990.0

In [515]:
dados[1,2]

1990.0

 ### Fatiamentos
 
A sintaxe para realizar fatiamento em um array Numpy é $i : j : k$ onde $i$ é o índice inicial, $j$ é o índice de parada, e $k$ é o indicador de passo ($k\neq0$)
 
<font color=red>**Observação:**</font> Nos fatiamentos (*slices*) o item com índice i é **incluído** e o item com índice j **não é incluído** no resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [516]:
contador[1:4]

array([1, 2, 3])

In [517]:
contador[1:8:2]

array([1, 3, 5, 7])

In [518]:
contador[::2]

array([0, 2, 4, 6, 8])

In [519]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [520]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [521]:
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [522]:
dados[:,1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [523]:
dados[:,1:3][0]

array([ 5712., 37123.])

In [524]:
dados[:,1:3][0]/(2022 - dados[:,1:3][1])

array([ 184.25806452, 1160.09375   ])

In [525]:
dados[0]/(2022 - dados[1])

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

### Indexação com array booleano

<font color=red>**Observação:**</font> Seleciona um grupo de linhas e colunas segundo os rótulos ou um array booleano.

In [526]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [527]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [528]:
contador[contador > 5]

array([6, 7, 8, 9])

In [529]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [530]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [531]:
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

In [541]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteiro', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casado', 'feminino']
    ]
)

In [542]:
dados

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteiro', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casado', 'feminino']], dtype='<U9')

In [543]:
dados.shape

(4, 3)

In [544]:
dados[:, 2] 

array(['masculino', 'feminino', 'masculino', 'feminino'], dtype='<U9')

In [545]:
dados[:, 2]  == 'masculino'

array([ True, False,  True, False])

In [548]:
dados[dados[:, 2]  == 'masculino']

array([['Roberto', 'casado', 'masculino'],
       ['Bruno', 'solteiro', 'masculino']], dtype='<U9')

In [549]:
dados[::2]

array([['Roberto', 'casado', 'masculino'],
       ['Bruno', 'solteiro', 'masculino']], dtype='<U9')

In [551]:
dados[:2, :2]

array([['Roberto', 'casado'],
       ['Sheila', 'solteiro']], dtype='<U9')

In [552]:
dados[0::2, :2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [553]:
dados[:2, 0::2]

array([['Roberto', 'masculino'],
       ['Sheila', 'feminino']], dtype='<U9')

# 5.4 Atributos e métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [555]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]
dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Retorna uma tupla com as dimensões do array.

In [556]:
dados.shape

(2, 5)

## *ndarray.ndim*

Retorna o número de dimensões do array.

In [557]:
dados.ndim

2

## *ndarray.size*

Retorna o número de elementos do array.

In [558]:
dados.size

10

## *ndarray.dtype*

Retorna o tipo de dados dos elementos do array.

In [559]:
dados.dtype

dtype('float64')

## *ndarray.T*

Retorna o array transposto, isto é, converte linhas em colunas e vice versa.

In [560]:
dados.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [561]:
dados.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Retorna o array como uma lista Python.

In [562]:
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

In [563]:
type(dados.tolist())

list

## *ndarray.reshape(shape[, order])*

Retorna um array que contém os mesmos dados com uma nova forma.

In [564]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [566]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [567]:
contador.reshape((5,2), order = "C")

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [568]:
contador.reshape((5,2), order = "F")

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [569]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [570]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [572]:
np.array(info_carros).reshape((5,2))

array([[44410,  5712],
       [37123,     0],
       [25757,  2003],
       [ 1991,  1990],
       [ 2019,  2006]])

In [573]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [575]:
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Altera a forma e o tamanho do array.

In [576]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [578]:
dados_new.resize((3,5), refcheck=False)

In [579]:
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [580]:
dados_new[2] = dados_new[0]/(2022 - dados_new[1])

In [581]:
dados_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2337.36842105,   184.25806452,  1160.09375   ,     0.        ,
         1609.8125    ]])

# 5.5 Estatísticas com arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

e

https://numpy.org/doc/1.16/reference/routines.statistics.html

e

https://numpy.org/doc/1.16/reference/routines.math.html

In [582]:
anos = np.loadtxt(fname = "carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [583]:
anos.shape

(258,)

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [584]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [585]:
dataset.shape

(258, 3)

## *np.mean()*

Retorna a média dos elementos do array ao longo do eixo especificado.

In [586]:
np.mean(dataset)

48489.14648578811

In [587]:
np.mean(dataset, axis=0) # colunas

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [588]:
np.mean(dataset, axis=1) #linhas

array([44830.54666667, 37954.98      , 37315.05333333, 42189.35666667,
       40125.03333333, 36745.91      , 19488.06666667, 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18400.79333333, 56984.80666667, 59177.8       ,
       36526.53      , 30190.46333333, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.46666667, 77867.61333333, 76878.21666667,
       41205.07      , 24462.03333333, 34386.25      , 35817.28      ,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.19666667, 41766.95666667, 25768.39333333, 34876.18      ,
       54475.06333333, 59333.43      , 29553.44666667, 75040.79666667,
       39881.91      , 22655.23333333, 52057.21666667, 31725.88333333,
       22240.03333333, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [589]:
np.mean(dataset[:,1])

44499.41472868217

In [590]:
np.mean(dataset[:,2])

98960.51310077519

## *np.std()*

Retorna o desvio padrão dos elementos do array ao longo do eixo especificado.

In [591]:
np.std(dataset)

48982.75759118537

## *ndarray.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [593]:
dataset.sum(axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [594]:
dataset[:, 1].sum()

11480849.0

## *np.sum()*

Retorna a soma dos elementos do array ao longo do eixo especificado.

In [595]:
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [596]:
np.sum(dataset[:,2])

25531812.38

In [597]:
np.sum(dataset[:,1])

11480849.0

In [598]:
idades = np.array([10, 23, 45, 34, 25])

In [599]:
np.mean(idades)

27.4

In [600]:
np.sum(idades)/idades.size

27.4

In [602]:
idades.mean()

27.4